(source gnu)
(source melpa)

(depends-on "alchemist")
(depends-on "diff-hl")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "json-mode")
(depends-on "neotree")
(depends-on "nvm")
(depends-on "web-mode")
(depends-on "zenburn-theme")